# Generated by Django 5.2.6 on 2025-10-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
