# Generated by Django 5.2.6 on 2025-10-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_remove_user_address_remove_user_city_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
