# Generated by Django 5.2.6 on 2025-11-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default='False', max_length=255),
        ),
    ]
